project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links:
    - text: Repository of this manuscript
      icon: github
      href: https://github.com/m-delem/2499-similarity-manuscript

format:
  html:
    # color theme
    theme:
      dark: darkly
      light: darkly
    # formatting
    fontsize: "medium"
  docx: default
  jats: default
  elsevier-pdf:
    journal:
      cite-style: authoryear
    include-in-header:
      text: |
        \newpageafter{abstract}

execute:
  freeze: auto
  # code reading options
  warning: false
  error: false
  message: false

# dates
date-format: "D/MM/YYYY"
date: 2024-02-02
date-modified: last-modified

# table of contents
toc: true
toc-location: left
toc-depth: 2
toc-expand: 1
number-sections: true
number-depth: 2

# figures and captions
fig-format: svg
cap-location: top
fig-cap-location: bottom
tbl-cap-location: top

# code
code-annotations: hover

# setting for proper numbering of sections
crossref:
  chapters: true


